# Generated by Django 5.0.1 on 2024-03-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentAuthor',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reviewId',
            new_name='review_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='albumId',
            new_name='album_id',
        ),
    ]
